"""
Derive a 10-task list draft from 30_DAY_IMPLEMENTATION_STATUS and 30_DAY_SCHEDULE.
Uses docs/workflow/30DAY_TO_10TASK_MAPPING.json for bucket (T1-T10) to day ranges.
Output: draft to stdout or Saved/Logs/current_task_list_draft.md; does not overwrite
CURRENT_TASK_LIST.md unless --write is passed.
Run from project root: python Content/Python/migrate_30day_to_task_list.py [--write]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
DOCS_WORKFLOW = PROJECT_ROOT / "docs" / "workflow"
STATUS_PATH = DOCS_WORKFLOW / "30_DAY_IMPLEMENTATION_STATUS.md"
SCHEDULE_PATH = DOCS_WORKFLOW / "30_DAY_SCHEDULE.md"
MAPPING_PATH = DOCS_WORKFLOW / "30DAY_TO_10TASK_MAPPING.json"
TASK_LIST_PATH = DOCS_WORKFLOW / "CURRENT_TASK_LIST.md"
DRAFT_PATH = PROJECT_ROOT / "Saved" / "Logs" / "current_task_list_draft.md"

TASK_IDS = [f"T{i}" for i in range(1, 11)]


def _parse_status_table(path: Path) -> dict[int, str]:
    """Parse 30_DAY_IMPLEMENTATION_STATUS table: day (1-30) -> status (done/pending/blocked)."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    result: dict[int, str] = {}
    for line in lines:
        # Table row: | 1 | PCG forest | done | Notes |
        m = re.match(r"^\|\s*(\d+)\s*\|\s*[^|]+\|\s*(\S+)\s*\|", line.strip())
        if m:
            day = int(m.group(1))
            status = m.group(2).lower()
            if 1 <= day <= 30:
                result[day] = status
    return result


def _parse_schedule_overview(path: Path) -> dict[int, tuple[str, str]]:
    """Parse Day-by-day overview table: day -> (focus, description)."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    result: dict[int, tuple[str, str]] = {}
    in_table = False
    for line in lines:
        stripped = line.strip()
        if "| Day | Focus |" in stripped and "Task IDs" in stripped:
            in_table = True
            continue
        if in_table and stripped.startswith("|---"):
            continue
        if in_table and stripped.startswith("|"):
            parts = [p.strip() for p in stripped.split("|") if p.strip()]
            if len(parts) >= 3 and parts[0].isdigit():
                day = int(parts[0])
                if 1 <= day <= 30:
                    result[day] = (parts[1], parts[2] if len(parts) > 2 else "")
            elif "–" in parts[0] or "-" in parts[0]:
                # e.g. 26–30
                continue
        if in_table and stripped and not stripped.startswith("|"):
            break
    return result


def _load_mapping(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _render_task_list(
    day_status: dict[int, str],
    schedule: dict[int, tuple[str, str]],
    mapping: dict,
) -> str:
    buckets = mapping.get("buckets") or {}
    lines = [
        "# Current task list (10-task) – draft from 30-day",
        "",
        "**Purpose:** Single ordered list that drives the automation loop. Generated by migrate_30day_to_task_list.py.",
        "",
        "**Convention:** `pending` | `in_progress` | `completed` | `blocked`",
        "",
        "---",
        "",
    ]
    for tid in TASK_IDS:
        info = buckets.get(tid, {})
        day_nums = info.get("days") or []
        label = info.get("label") or "Buffer / reserved"
        if day_nums:
            all_done = all(day_status.get(d) == "done" for d in day_nums)
            status = "completed" if all_done else "pending"
            first_day = day_nums[0]
            focus, desc = schedule.get(first_day, ("", ""))
            goal = f"{label}. Days {min(day_nums)}–{max(day_nums)}: {focus}; {desc}" if focus else f"{label} (days {min(day_nums)}–{max(day_nums)})."
            goal = goal.strip(" ;")
        else:
            status = "completed"
            goal = "Reserved for next priority; replace with a concrete task from research when generating a new list."
        lines.append(f"## {tid}. {label}")
        lines.append("")
        lines.append(f"- **goal:** {goal}")
        lines.append(f"- **success criteria:** (Fill from 30-day or VERTICAL_SLICE_CHECKLIST when replacing list.)")
        lines.append(f"- **research_notes:** (Fill from VISION, AUTOMATION_GAPS, or task docs.)")
        lines.append(f"- **steps_or_doc:** (Links to task docs.)")
        lines.append(f"- **status:** {status}")
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Migrate 30-day status to 10-task list draft.")
    parser.add_argument("--write", action="store_true", help="Overwrite CURRENT_TASK_LIST.md (default: emit draft only)")
    args = parser.parse_args()

    day_status = _parse_status_table(STATUS_PATH)
    schedule = _parse_schedule_overview(SCHEDULE_PATH)
    mapping = _load_mapping(MAPPING_PATH)
    if not mapping or "buckets" not in mapping:
        print("Migration: 30DAY_TO_10TASK_MAPPING.json missing or invalid.", file=sys.stderr)
        return 1

    draft = _render_task_list(day_status, schedule, mapping)

    if args.write:
        TASK_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
        TASK_LIST_PATH.write_text(draft, encoding="utf-8")
        print(f"Wrote {TASK_LIST_PATH}", file=sys.stderr)
        return 0

    # Emit draft to Saved/Logs (avoid stdout to prevent Windows console encoding errors)
    DRAFT_PATH.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_PATH.write_text(draft, encoding="utf-8")
    print(f"Draft written to {DRAFT_PATH}", file=sys.stderr)
    print("Copy to docs/workflow/CURRENT_TASK_LIST.md and add research_notes as needed.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
