"""
Verify 30-day implementation: check key artifacts (scripts, C++ headers, configs) per day.
Writes Saved/Logs/verify_30day_report.md. Run from project root: py Content/Python/verify_30day_implementation.py
"""
from __future__ import annotations

import os
import json
from pathlib import Path

# Project root = parent of Content
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
CONTENT = PROJECT_ROOT / "Content"
SOURCE = PROJECT_ROOT / "Source" / "HomeWorld"
SAVED_LOGS = PROJECT_ROOT / "Saved" / "Logs"
PYTHON_DIR = CONTENT / "Python"

# Per-day checks: (description, list of paths to check - file or dir)
DAY_CHECKS = [
    (1, "PCG forest", [
        CONTENT / "HomeWorld" / "PCG" / "ForestIsland_PCG.uasset",
        PYTHON_DIR / "create_pcg_forest.py",
    ]),
    (2, "GAS + character", [
        PYTHON_DIR / "setup_gas_abilities.py",
        SOURCE / "HomeWorldCharacter.h",
    ]),
    (3, "Placement + playtest", [
        SOURCE / "BuildPlacementSupport.h",
    ]),
    (4, "Polish + optional Milady", [
        CONTENT / "HomeWorld" / "Milady",
    ]),
    (5, "Playtest sign-off", []),  # No artifact check
    (6, "Homestead layout", [
        PYTHON_DIR / "demo_map_config.json",
        CONTENT / "HomeWorld" / "Maps" / "DemoMap.umap",
    ]),
    (7, "Resource nodes", [
        PYTHON_DIR / "create_bp_harvestable_tree.py",
        PYTHON_DIR / "place_resource_nodes.py",
    ]),
    (8, "Resource collection", [
        SOURCE / "HomeWorldInteractAbility.h",
    ]),
    (9, "Home placement", [
        SOURCE / "HomeWorldPlaceAbility.h",
    ]),
    (10, "Agentic building", [
        SOURCE / "HomeWorldBuildOrder.h",
    ]),
    (11, "Family spawn", [
        PYTHON_DIR / "create_mec_family_gatherer.py",
        PYTHON_DIR / "link_state_tree_to_mec.py",
    ]),
    (12, "Protector", [
        SOURCE / "HomeWorldProtectorAttackAbility.h",
    ]),
    (13, "Healer", [
        PYTHON_DIR / "create_ga_heal.py",
        SOURCE / "HomeWorldHealAbility.h",
    ]),
    (14, "Child", []),  # Doc/design
    (15, "Role persistence", [
        SOURCE / "HomeWorldFamilySubsystem.h",
    ]),
    (16, "Planetoid level", [
        PYTHON_DIR / "ensure_planetoid_level.py",
        PYTHON_DIR / "place_portal_placeholder.py",
        PYTHON_DIR / "planetoid_map_config.json",
    ]),
    (17, "PCG POI", [
        PYTHON_DIR / "create_bp_poi_placeholders.py",
        PYTHON_DIR / "create_planetoid_poi_pcg.py",
        CONTENT / "HomeWorld" / "PCG" / "Planetoid_POI_PCG.uasset",
    ]),
    (18, "Shrine, Treasure", []),  # Tags / same placeholders
    (19, "Cultivation, Mining", [
        SOURCE / "HomeWorldYieldNode.h",
        PYTHON_DIR / "create_bp_yield_nodes.py",
    ]),
    (20, "Visit and interact", []),
    (21, "Death, spirit roster", [
        SOURCE / "HomeWorldSpiritRosterSubsystem.h",
    ]),
    (22, "Assign spirit, yield", [
        SOURCE / "HomeWorldSpiritAssignmentSubsystem.h",
    ]),
    (23, "Unassign spirit", []),  # Same subsystem
    (24, "Dungeon POI", [
        PYTHON_DIR / "place_dungeon_entrance.py",
        PYTHON_DIR / "dungeon_map_config.json",
    ]),
    (25, "Boss, reward", []),
    (26, "Buffer", []),
    (27, "Buffer", []),
    (28, "Buffer", []),
    (29, "Buffer", []),
    (30, "Buffer", []),
]


def main() -> None:
    SAVED_LOGS.mkdir(parents=True, exist_ok=True)
    report_path = SAVED_LOGS / "verify_30day_report.md"
    results = []
    all_ok = True

    for day, focus, paths in DAY_CHECKS:
        if not paths:
            results.append((day, focus, True, ["(no artifact check)"]))
            continue
        missing = []
        for p in paths:
            if not p.exists():
                missing.append(str(p.relative_to(PROJECT_ROOT)))
        ok = len(missing) == 0
        if not ok:
            all_ok = False
        results.append((day, focus, ok, missing))

    lines = [
        "# 30-day implementation verification report",
        "",
        f"Generated by verify_30day_implementation.py",
        "",
        "| Day | Focus | Status | Missing / notes |",
        "|-----|--------|--------|-----------------|",
    ]
    for day, focus, ok, missing in results:
        status = "OK" if ok else "MISSING"
        note = "; ".join(missing) if missing else "-"
        lines.append(f"| {day} | {focus} | {status} | {note} |")

    lines.extend([
        "",
        "**Summary:** " + ("All checked artifacts present." if all_ok else "Some artifacts missing (see table)."),
        "",
    ])
    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Verify 30-day: report written to {report_path.relative_to(PROJECT_ROOT)}")
    if not all_ok:
        for day, focus, ok, missing in results:
            if not ok and missing:
                print(f"  Day {day} ({focus}): missing {missing}")
    return None


if __name__ == "__main__":
    main()
